apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /mnt/config
          name: myvolume
  volumes:
    - name: myvolume
      configMap:
        name: mycm
