apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              key: HOST
              name: mycm
