apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  securityContext:
    runAsUser: 20
    runAsGroup: 20
  containers:
    - name: hello
      image: bash
      args:
        - sleep
        - "3600"

