apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80
      name: nginx
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: backend
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
