apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: USER
          valueFrom:
            secretKeyRef: # get value of "user" key, look in "mysecret" secret
              name: mysecret
              key: user

