apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts: # mount volume
        - mountPath: /mnt
          name: mysecret
  volumes:
    - name: mysecret # create volume from secret
      secret:
        secretName: mysecret
