apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: nginx
      volumeMounts:
        - name: myvolume
          mountPath: "/projected-volume"
          readOnly: true
  volumes:
    - name: myvolume
      projected:
        sources:
          - secret:
              name: user # from first secret
          - secret:
              name: pass # from second secret

